use exporter-toolkit to add TLS and Basic Auth
RichiH/modbus_exporter pull request #37
Opened 2022-10-18 12:31 UTC by fschlich

This is mostly copied from SNMP and Redfish exporters, and requires a go-kit based logger. README.md mentions "Rework logging" as TODO, but doesn't mention any specifics - I personally wouldn't need levels for example...

2022-10-21 01:10 UTC, RichiH commented
Also tagging @SuperQ for potential pair of eyes as it's taking things from snmp exporter.

2022-10-21 10:43 UTC, SuperQ requested changes

2022-10-21 10:43 UTC, SuperQ commented on go.mod
> +	github.com/prometheus/exporter-toolkit v0.5.0
This is a very old version, you should probably update this to the latest. We have simplified the interface and flags. See https://github.com/prometheus/node_exporter/pull/2393.

2022-10-25 20:07 UTC, SuperQ commented on go.mod
> +	github.com/prometheus/exporter-toolkit v0.5.0
`--telemetry-listen-address` will be replaced by the exporter toolkit `--web.listen-address`. The `--modbus-listen-address` will stay the same. But should probably be renamed to match the usual Prometheus conventions.

2023-03-10 04:59 UTC, DaAwesomeP commented
@fschlich any updates on this pull?

2023-03-10 17:22 UTC, DaAwesomeP commented
@fschlich Sounds good! I will create a new pull request with the latest exporter-toolkit and modbus_exporter branches.  I will potentially cherry pick your changes.

2023-03-11 17:01 UTC, closed without merging